name: Add Labels to Pull Request

on:
  workflow_call:

permissions:
  # Setting up permissions in the workflow to limit the scope of what it can do.
  pull-requests: write # for labeling pull requests (on: pull_request)
  statuses: write # to generate status
  checks: write # to generate status

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v2
        with:
          config-repo: modyo-connect/.github
          config-path: .github/modyo-labeler.yml