name: test wf

on:
  push:
    branches:
      - test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Push changes
        run: |
          echo $PRUEBA
        env:
          PRUEBA: HOLA